name: pipelines-codechecks-mslearn-mlops1

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - cli/jobs/pipelines/mslearn-mlops/model/*.py
  #    - infra/bootstrapping/**
  #    - .github/workflows/mslearn-mlops1.yml
  #    - cli/run-pipeline-jobs.sh
  #    - cli/setup.sh
jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 model/
      working-directory: cli/jobs/pipelines/mslearn-mlops
  job2:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "${{ github.workspace }}/requirements.txt"      
    - name: Run ML Unit tests/
      run: | 
        pytest tests/
      working-directory: cli/jobs/pipelines/mslearn-mlops



